config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get '/signup', to: 'static_pages#signup'
  post '/signup', to: 'organizations#create'
  get '/login', to: 'static_pages#login'
  get '/auth/facebook/callback' => 'sessions#create_fb'
  post '/login', to: 'sessions#create'
  post '/sessions/create', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/employees/ofthemonth', to: 'employees#month'
  
  resources :organizations do
    resources :employees, shallow: true
  end

  resources :projects, shallow: true do
    resources :tasks
  end

  resources :comments, only: [:index, :new, :create, :show]
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end

    def login
    end

    def signup
        @new_org = Organization.new
    end
end

app/views/static_pages/home.html.erb
<h1>Welcome To Round Table Task Management</h1>

<%= link_to 'Log In Here', login_path %><br>

<%= link_to 'Sign Up Your Organization Here', signup_path %>

app/views/static_pages/login.html.erb
<h1>Login Here</h1>

<%# Create login form here %>
<%# credentials: email, password %>
<%= render 'sessions/login_form' %><br>

<%= link_to('Log in with Facebook!', '/auth/facebook') %>

<%# link_to 'Sign In', employee_path(@employee) %>

app/views/static_pages/signup.html.erb
<h1> Sign Up Here</h1>

<%= render partial: 'layouts/error_message', locals: {object: @new_org} %>

<%= render 'organizations/form' %>