config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get '/signup', to: 'static_pages#signup'
  post '/signup', to: 'organizations#create'
  get '/login', to: 'static_pages#login'
  get '/auth/facebook/callback' => 'sessions#create_fb'
  post '/login', to: 'sessions#create'
  post '/sessions/create', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/employees/ofthemonth', to: 'employees#month'
  
  resources :organizations do
    resources :employees, shallow: true
  end

  resources :projects, shallow: true do
    resources :tasks
  end

  resources :comments, only: [:index, :new, :create, :show]
  
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_secure_password

    belongs_to :organization
    has_many :tasks
    has_many :projects, through: :tasks
    has_many :comments

    validates :email, format: { with: /\A[a-zA-Z0-9.!\#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])+\.[a-z](?:[a-z]{0,2}[a-z])\z/ }, presence: true, uniqueness: true
    validates :first_name, presence: true

    def full_name
        self.first_name + ' ' + self.last_name
    end
    
    def assigned_tasks
        self.tasks.select do |task|
            task.completed == false
        end
    end

    def completed_tasks
        self.tasks.select do |task|
            task.completed == true
        end
    end
    

    def self.most_completed_tasks
        self.all.sort_by {|emp| emp.completed_tasks.count }.last
    end



    private

    @email_regexp = /\A[a-zA-Z0-9.!\#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])+\.[a-z](?:[a-z]{0,2}[a-z])\z/


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :require_login, only: [:index, :show, :edit, :update, :destroy] #TODO Find a solution to this workaround
    before_action :set_employee, only: [:show, :edit, :update, :destroy]
    before_action :set_user

    def index
        @employees = current_org_employees
    end
    
    def new
        @employee = Employee.new
        @organization = Organization.find(params[:organization_id])
    end

    def create
        @employee = Employee.new(employee_params)
        @organization = Organization.find(params[:organization_id]) if params[:organization_id]
        if @employee.save
            if !session[:employee_id] #if valid data && there is no existing employee_id in session hash (i.e. creating first employee for new organization)
                session[:employee_id] = @employee.id
                session[:organization_id] = @employee.organization_id
                redirect_to employee_path(@employee)
            else # same as above, but there is an existing employee_id in session hash (i.e. project lead is creating new employee)
                redirect_to employee_path(@employee) #TODO flash message that employee was successfully created
            end
        else
            render :new
        end
    end

    def show
        @assigned = @employee.assigned_tasks
        @completed = @employee.completed_tasks
        respond_to do |format|
            format.html { render :show }
            format.json { render json: @employee, status: 201}
        end
    end

    def edit
        if :project_lead?
            @organization = Organization.find(session[:organization_id]) 
            render "edit"
        else
            return head(:forbidden)
        end
    end

    def update
        @organization = Organization.find(session[:organization_id])
        if :project_lead?
            if @employee.update(employee_params)
                redirect_to employee_path(@employee)
            else
                render :edit
            end
        else
            return head(:forbidden)
        end
    end

    def destroy
        if :project_lead?
            @employee.tasks.each do |task|
                task.employee_id = nil
            end
            @employee.destroy
            redirect_to projects_path
        else
            return head(:forbidden)
        end
    end

    def month
        org = Organization.find(session[:organization_id])
        @emp_month = org.employees.most_completed_tasks
    end

    private

    def employee_params
        params.require(:employee).permit(:first_name, :last_name, :title, :password, :email, :lead, :password_confirmation, :organization_id)
    end

    def set_employee
        @employee = Employee.find(params[:id])
        require_org_permission(@employee.organization_id)
    end

    def current_org_employees
        Employee.all.select {|emp| emp.organization_id == session[:organization_id]}
    end
   
end

app/helpers/employees_helper.rb
module EmployeesHelper

    def due_or_completed_time(task)
        if task.status == 'Completed'
            "Task completed at #{task.updated_at.strftime("%A, %b %e")}"
        elsif task.status == 'In Progress' && !task.due_date.nil?
            "Task due at #{due_date_formatted(task)}"
        else
            "No due date specified"
        end
    end

    
end

app/views/employees/_form.html.erb
<%= form_for @employee, url: url, method: method do |f| %>
    <% if params[:organization_id] %>
        <%= f.hidden_field :organization_id, value: params[:organization_id] %>
    <% else %>
        <%= f.hidden_field :organization_id, value: @employee.organization_id %>
    <% end %>
    
    Personal Information<br>
    First Name: <%= f.text_field :first_name %>
    Last Name: <%= f.text_field :last_name %>
    Title: <%= f.text_field :title %><br>
    <br>
    Log In Information<br>
    Email: <%= f.text_field :email %>
    Password: <%= f.password_field :password %>
    Confirm Password: <%= f.password_field :password_confirmation %><br>

    <% if @organization.employees.empty? %>
        <%= f.hidden_field :lead, value: true %>
    <% else %>
        <%= f.check_box :lead, {}, "true", "false" %> Check here for Project Lead<br>
    <% end %>

    <%= f.submit "Submit"%>
<% end %>

app/views/employees/edit.html.erb
<h2>Edit This Employee:</h2>

<%= render partial: 'layouts/error_message', locals: {object: @employee} %>

<%= render partial: 'employees/form', locals: {url: employee_path(@employee), method: 'patch'} %>

app/views/employees/index.html.erb
<h2>Employee Directory</h2>

<ul>
<% @employees.each do |emp| %>
    <li><%= link_to emp.full_name, employee_path(emp) %> - <%= emp.title %></li>
<% end %>
</ul><br>

app/views/employees/month.html.erb
<%= @emp_month.full_name %>

<p><%= @emp_month.full_name %> completed <%= @emp_month.completed_tasks.count %> tasks this month. Good job!</p>

app/views/employees/new.html.erb
<h2>Create a New Employee:</h2>

<%= render partial: 'layouts/error_message', locals: {object: @employee} %>

<%= render partial: 'employees/form', locals: {url: {controller: 'employees', action: 'create'}, method: 'post'}  %>

app/views/employees/show.html.erb
<h1 id="empGreeting"></h1>

<div id="infoPanel">
    <span id="empBasicInfo">
        <h2>Title:</h2>
        <h4 id="empTitle"></h4>

        <h2>Email:</h2>
        <h4 id="empEmail"></h4>

        <h2>Project Lead?</h2>
        <h4 id="empLead"></h4><br>
    </span>

    <span id="leadPanel">
        <% if @curr_user.lead %>
            <% if @employee == @curr_user %>
                <%= link_to 'Add Employee', new_organization_employee_path(@employee.organization.id)%>
            <% else %>
                <%= link_to 'Edit Employee', edit_employee_path(@employee) %>
                <%= link_to 'Delete Employee', employee_path(@employee), method: :delete, data: {confirm: "Are you sure you want to delete this employee? This will unassign their tasks and remove their profile."} %>
            <% end %>
        <% end %>
    </span>
    <span>
        <% if @employee == @curr_user %>
            <%= link_to 'Edit Your Profile', edit_employee_path(@employee) %>
        <% end %>
    </span>
</div>


<div id='empTasks'>
    <h2>Currently Working On:</h2>
    <ul id="empAssignedTasks"></ul>

    <h2>Recently Completed:</h2>
    <ul id="empCompletedTasks"></ul>
</div>