config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get '/signup', to: 'static_pages#signup'
  post '/signup', to: 'organizations#create'
  get '/login', to: 'static_pages#login'
  get '/auth/facebook/callback' => 'sessions#create_fb'
  post '/login', to: 'sessions#create'
  post '/sessions/create', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/employees/ofthemonth', to: 'employees#month'
  
  resources :organizations do
    resources :employees, shallow: true
  end

  resources :projects, shallow: true do
    resources :tasks
  end

  resources :comments, only: [:index, :new, :create, :show]
  
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :organization
    has_many :tasks
    has_many :employees, through: :tasks
    has_many :comments, through: :tasks

    validates :name, presence: true

    def unassigned_project_tasks
        self.tasks.select {|task| task.status == "Unassigned"}
    end

    def assigned_project_tasks
        self.tasks.select {|task| task.status == "In Progress"}
    end

    def completed_project_tasks
        self.tasks.select {|task| task.status == "Completed"}
    end

    def self.active_project_ids(org_id)
        where(organization_id: Organization.find(org_id)).pluck(:id)
    end

    def self.active_projects(org_id)
        self.active_project_ids(org_id).map do |id|
            self.find_by(id: id)
        end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :require_login
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    before_action :set_user, only:[:index, :new, :create, :edit, :update, :show]

    def index
        @projects = Project.active_projects(params[:organization_id]) if params[:organization_id]
        respond_to do |format|
            format.html { render "/projects/index" }
            format.json { render json: @projects, status:201 }
        end
    end
    
    def new
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)
        if @project.save
            redirect_to project_path(@project)
        else
            render :new
        end
    end

    def show
    end

    def edit
        if :project_lead?
            render "edit"
        else
            return head(:forbidden)
        end
    end

    def update
        if :project_lead?
            if @project.update(project_params)
                redirect_to project_path(@project)
            else
                render :edit
            end
        else
            return head(:forbidden)
        end
    end

    def destroy
        if :project_lead?
            @project.tasks.each do |task|
                task.comments.each do |comment|
                    comment.destroy
                end
                task.destroy
            end
            @project.destroy
            redirect_to projects_path
        else
            return head(:forbidden)
        end
    end

    private

    def project_params
        params.require(:project).permit(:name, :due_date, :description, :organization_id, :lead_id)
    end

    def set_project
        @project = Project.find(params[:id])
        require_org_permission(@project.organization_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def project_lead_name(project)
        lead = Employee.find_by(id: project.lead_id) if project.lead_id
        "#{lead.full_name}"
    end

    def deadline_formatted(project) #TODO: delete this and replace with app_helper method
        project.due_date.strftime("%A, %b %e")
    end
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
    <%= f.hidden_field :lead_id, value: @curr_user.id%>
    <%= f.hidden_field :organization_id, value: @curr_user.organization.id%>
    Project Name: <%= f.text_field :name %>
    Description: <%= f.text_area :description %>
    Due Date: <%= f.date_select :due_date, default: Date.today %>
    <%= f.submit "Submit Project" %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit This Project</h1>

<%= render partial: 'layouts/error_message', locals: {object: @project} %>

<%= render 'form'%>

app/views/projects/index.html.erb
<h1>Active Projects</h1>

<ul id="projectList">
<%
=begin%>
<% @projects.each do |project| %>
    <li><%= link_to project.name, project_path(project) %></li>
<% end %>
<%
=end%>

</ul><br>

<br>

<% if @curr_user.lead %>
    <h4><%= link_to "Create New Project", new_project_path %></h4>
<% end %>

app/views/projects/new.html.erb
<h1>Create A New Project</h1>

<%= render partial: 'layouts/error_message', locals: {object: @project} %>

<%= render 'form'%>

app/views/projects/show.html.erb
<h2>Project: <%= @project.name %></h2>

<% if @curr_user.lead && @project.lead_id == @curr_user.id %>
    <%= link_to "Edit This Project", edit_project_path(@project) %>
    <%= link_to 'Delete This Project', project_path(@project), method: :delete, data: {confirm: "Are you sure you want to delete this project? This will also delete its related tasks and their comments."} %>
<% end %>
<br>

<h3>Deadline: <%= due_date_formatted(@project) %></h3>

<h3>Description:</h3>
<p><%= @project.description %></p><br>

<h3>Project Lead: <%= project_lead_name(@project) %></h3><br>

<h3>Employees Currently Participating:</h3>
<ul>
<% @project.employees.uniq.each do |employee| %>
    <li><%= link_to employee.full_name, employee_path(employee) %> - <%= employee.title %></li>
<% end %>
</ul><br>


<h3>Unassigned Tasks:</h3>
<ul>
<% @project.unassigned_project_tasks.each do |task| %>
    <li><%= link_to task.content, task_path(task) %></li>
<% end %>
</ul><br>

<% if @curr_user.lead %>
    <%= link_to "Add a New Task", new_project_task_path(@project.id) %>
<% end %>

<h3>In Progress Tasks:</h3>
<ul>
<% @project.assigned_project_tasks.each do |task| %>
    <li><%= link_to task.content, task_path(task) %></li>
<% end %>
</ul><br>

<h3>Recently Completed Tasks</h3>
<ul>
<%# add in limit to completed_project_tasks %>
<% @project.completed_project_tasks.each do |task| %>
    <li><%= link_to task.content, task_path(task) %></li>
<% end %>
</ul><br>