config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get '/signup', to: 'static_pages#signup'
  post '/signup', to: 'organizations#create'
  get '/login', to: 'static_pages#login'
  get '/auth/facebook/callback' => 'sessions#create_fb'
  post '/login', to: 'sessions#create'
  post '/sessions/create', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/employees/ofthemonth', to: 'employees#month'
  
  resources :organizations do
    resources :employees, shallow: true
  end

  resources :projects, shallow: true do
    resources :tasks
  end

  resources :comments, only: [:index, :new, :create, :show]
  
end

app/views/layouts/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roundtable: <%# Organization.find(session[:organization_id]).name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <div class="container">
      <header>
        <% if session[:employee_id] %>
          <h1>Welcome to Roundtable Task Management for <%= curr_employee.organization.name %></h1>
          <h3>Currently Logged In As: <%= link_to curr_employee_name, employee_path(curr_employee) %></h3>
        <% end %>
      </header>

      <%=content_tag "main", class: "#{controller_name} #{action_name}", data: {id: params[:id], curr_user_id: @curr_user.id, organization_id: session[:organization_id]} do %>
        <%= yield %>
      <% end %>

      <footer>
        <% if session[:employee_id] %>
          <%= link_to "Project Directory", projects_path %>
          <%= link_to "Employee Directory", organization_employees_path(session[:organization_id]) %>
          <%= link_to "Log Out", logout_path, method: :delete %>
        <% else %>
          <%= link_to "Home Page", root_path %>
        <% end %>

        <p>&copy; 2019 Daniel Schoch</p>
      </footer>
    </div>
   
    
  </body>

</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roundtable Task Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <%= yield %><br>

  </body>
</html>